config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'ideas#index'

  resources :ideas

  get 'likes/dislike', to: 'likes#dislike', as: :dislike
  resources :likes

  namespace 'api' do
    namespace 'v1' do
      get 'ideas' => 'ideas#index', defaults: { format: 'json'}
    end
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  include ActiveModel::Serialization

  belongs_to :user
  has_many :likes, dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true

  def likes_number
    likes = Like.where("idea_id = #{self.id}").reject{|like|like.value == nil}.map{|like|like.value }.inject(:+)
    likes == nil ? 0 : likes
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/ideas_controller.rb
class Api::V1::IdeasController < ApplicationController
  respond_to :json

  def index
    @ideas = []
    Idea.all.each do |idea|
     @ideas << idea.as_json(methods: :likes_number)
    end

    respond_to do |format|
      format.json { render json: @ideas }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @ideas = Idea.all.sort_by{|idea|idea.likes_number}.reverse
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to '/ideas'
    else
      render 'new'
    end
  end

  def idea_params
    params.require(:idea).permit(:name, :description)
  end

  def show
    if current_user
      @idea = Idea.find(params[:id])
    else
      flash[:notice] = 'Login to view comments'
      redirect_to '/ideas'
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)
    redirect_to '/ideas'
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    flash[:notice] = 'Idea deleted successfully'
    redirect_to '/ideas'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include LikesHelper

  def new
    add_like
    redirect_to :back
  end

  def dislike
    add_dislike
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper

  def add_like
    set_ideas_and_likes
    unless previous_like?
      new_plus_like
    end
    if previous_like_value == -1
      previous_like.first.destroy
    end
  end

  def add_dislike
    set_ideas_and_likes
    unless previous_like?
      new_dislike
    end
    if previous_like_value == 1
      previous_like.first.destroy
    end
  end

  def previous_like?
    previous_like.length == 1
  end

  def previous_like
    @likes.select {|like| like.user == current_user}
  end

  def previous_like_value
    previous_like? ? previous_like.first.value : 0
  end

  def new_plus_like
    Pusher.trigger('test_channel', 'my_event', {
      message: 'new like'
    })
    Like.create(user_id: current_user.id, idea: @idea, value: 1)
  end

  def new_dislike
    Pusher.trigger('test_channel', 'my_event', {
      message: 'new dislike'
    })
    Like.create(user_id: current_user.id, idea: @idea, value: -1)
  end

  def set_ideas_and_likes
    @idea = Idea.find(params[:idea_id])
    @likes = Like.where("idea_id = #{@idea.id}")
  end
end

app/views/ideas/edit.html.erb
<%= form_for @idea do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/ideas/index.html.erb
<table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable mdl-shadow--2dp">
<%if @ideas.any? %>
    <% @ideas.each do |idea|%>
      <tr>
        <td><%= link_to idea.name, idea_path(idea) %></td>
        <td><%= idea.description %></td>
        <td><%= idea.likes_number %></td>
        <td><i class="material-icons">thumb_up</i><%= link_to 'like', new_like_path({"idea_id" =>"#{idea.id}"}) %></td>
        <td><i class="material-icons">thumb_down</i><%= link_to 'dislike', dislike_path({"idea_id" =>"#{idea.id}"}) %></td>
      </tr>
    <% end %>
<% else %>
  <p>No ideas yet</p>

<% end %>
</table>
<% if user_signed_in? %>
  <br>
  <a href="/ideas/new" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Add an idea</a>
<% end %>

app/views/ideas/new.html.erb
<% if @idea.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@idea.errors.count, "error") %> prohibited this ridea from being saved: </h2>
    <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @idea do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/ideas/show.html.erb
<p><%= @idea.name %></p>
<p><%= @idea.description %></p>


<%= link_to "Edit", edit_idea_path(@idea) %>
<%= link_to "Delete", idea_path(@idea), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Idea Voter</span>
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation mdl-layout--large-screen-only">
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "mdl-navigation__link" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "mdl-navigation__link"%>
        <%= link_to "Sign up", new_user_registration_path, class: "mdl-navigation__link" %>
      <% end %>
      </nav>
    </div>
    </header>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
</body>
</html>